liip_imagine:
    filter_sets:
        # name our filter set "main_list"
        main_list:
            filters:
                thumbnail:
                    size: [64, 64]
                    mode: outbound
        karma:
            filters:
                thumbnail:
                    size: [28, 28]
                    mode: outbound